### ISSUE TITLE
SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by wmarti** [PrinceS25/StockAlertBot#11]
On a raspberry pi, get this error when running main.js:

/home/pi/Documents/StockAlertBot/main.js:31
export const OPEN_URL = true;   // true, false
^^^^^^

SyntaxError: Unexpected token export
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

I get the same error even when running the unedited git clone.

**Comment by wmarti** [comment]
Issue resolved when running with root privileges.
