### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by xoSpiderWebox** [PrinceS25/StockAlertBot#53]
```
SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

  Ran as root, still having trouble...
  it happens right after i execute node --experimental-modules main.js or
  node main.js

 I'm most likely missing dependencies but can't think of what I'm missing.

**Comment by xoSpiderWebox** [comment]
nevermind my node is not up to date.

**Comment by PrinceS25** [comment]
Hi. Sorry for the trouble. I'm sure you spent some time trying to get it working. Could you tell me your node version? You can check by doing `node -v`. 

Btw, don't ever run a random script you got online with root. 😛

**Comment by xoSpiderWebox** [comment]
Oh i'm not worried about that my friend, i'm just running it on a vps no worries. The box has nothing on it lol. just for testing this.
